service:
  name: eventum

frameworkVersion: ">=1.0.0 <2.0.0"

plugins:
  - serverless-webpack

custom:
  aws:
    region: eu-west-1
    dynamodb:
      events:
        tableName: ${self:service.name}-${self:provider.stage}-events
      snapshots:
        tableName: ${self:service.name}-${self:provider.stage}-snapshots
    kinesis:
      events:
        streamName: ${self:service.name}-${self:provider.stage}-events
    s3:
      prefix: ezequiel
      events:
        bucketName: ${self:custom.aws.s3.prefix}-${self:service.name}-${self:provider.stage}-events
  eventum:
    snapshot:
      retention:
        count: 2

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ${self:custom.aws.region}
  environment:
    EVENTS_TABLE_NAME: ${self:custom.aws.dynamodb.events.tableName}
    SNAPSHOTS_TABLE_NAME: ${self:custom.aws.dynamodb.snapshots.tableName}
    EVENTS_STREAM_NAME: ${self:custom.aws.kinesis.events.streamName}
    EVENTS_BUCKET_NAME: ${self:custom.aws.s3.events.bucketName}
    SNAPSHOT_RETENTION_COUNT: ${self:custom.eventum.snapshot.retention.count}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "arn:aws:lambda:*"
    # - Effect: "Allow"
    #   Action:
    #     - "kinesis:PutRecord"
    #     - "kinesis:PutRecords"
    #   Resource:
    #     Fn::GetAtt:
    #       - ${self:custom.aws.kinesis.events.streamName}
    #       - Arn

package:
  individually: true

functions:
  - ${file(serverless/api-functions.yml)}

resources:
  - ${file(serverless/dynamodb.yml)}
  - ${file(serverless/s3.yml)}
  # - ${file(serverless/kinesis.yml)}