Resources: 
  EventsDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.aws.dynamodb.events.tableName}
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
        - AttributeName: aggregateId
          AttributeType: S
        - AttributeName: sequence
          AttributeType: N
      KeySchema:
        - AttributeName: aggregateId
          KeyType: HASH
        - AttributeName: sequence
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: EventIdIndex
          KeySchema:
            - AttributeName: eventId
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  SnapshotsDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.aws.dynamodb.snapshots.tableName}
      AttributeDefinitions:
        - AttributeName: snapshotId
          AttributeType: S
        - AttributeName: aggregateId
          AttributeType: S
        - AttributeName: sequence
          AttributeType: N
      KeySchema:
        - AttributeName: aggregateId
          KeyType: HASH
        - AttributeName: sequence
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: SnapshotIdIndex
          KeySchema:
            - AttributeName: snapshotId
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  EventsDynamoDbTableArn:
    Value:
      Fn::GetAtt:
        - EventsDynamoDbTable
        - Arn
  EventsDynamoDbTableStreamArn:
    Value:
      Fn::GetAtt:
        - EventsDynamoDbTable
        - StreamArn
  SnapshotsDynamoDbTableArn:
    Value:
      Fn::GetAtt:
        - SnapshotsDynamoDbTable
        - Arn